name: "Static Analysis "

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  security-events: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: 
          - awsTerraGoat
          - azTerraGoat
          - awsGoat
          - azGoat

    steps:
      - name: Checkout the Main Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.repo }}

      - name: Create Infra Folder
        run: mkdir infra

      - name: Clone and Move KaiMonkey Files
        if: matrix.repo == 'awsMonkey'
        run: |
          git clone https://github.com/tenable/KaiMonkey.git
          mv KaiMonkey/terraform/aws/* infra/

      - name: Clone and Move Terragoat AWS Files
        if: matrix.repo == 'awsTerraGoat'
        run: |
          git clone https://github.com/octodemo/advanced-security-terraform.git
          mv advanced-security-terraform/terraform/aws/* infra/

      - name: Clone and Move Terragoat Azure Files
        if: matrix.repo == 'azTerraGoat'
        run: |
          git clone https://github.com/octodemo/advanced-security-terraform.git
          mv advanced-security-terraform/terraform/azure/* infra/

      - name: Clone and Move AWSGoat Files
        if: matrix.repo == 'awsGoat'
        run: |
          git clone https://github.com/ine-labs/AWSGoat.git
          mv AWSGoat/modules/* infra/

      - name: Clone and Move AzureGoat Files
        if: matrix.repo == 'azGoat'
        run: |
          git clone https://github.com/ine-labs/AzureGoat.git
          mv AzureGoat/modules/module-1/* infra/

      - name: Run Checkov in silent mode
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          output_format: sarif
          output_file_path: checkov-${{ matrix.repo }}.sarif
          quiet: true
        continue-on-error: true

      - name: Log after Checkov
        run: |
          echo "Checkov has completed. Moving to TFSec..."
          sleep 4
          ls -lias

      - name: Run TFSec SARIF Report
        uses: aquasecurity/tfsec-sarif-action@v0.1.0
        with:
          sarif_file: tfsec-${{ matrix.repo }}.sarif

      - name: Log after TFSec
        run: |
          echo "TFSec has completed. Zipping the SARIF files..."
          sleep 4
          ls -la

      - name: Zip all SARIF files
        run: |
          zip combined-sarif-${{ matrix.repo }}.zip *.sarif
          echo "Zipped all SARIF files to combined-sarif-${{ matrix.repo }}.zip"
          ls -la

          echo '{"version": "2.1.0", "runs": []}' > combined-${{ matrix.repo }}.sarif

          for file in *.sarif; do
              jq -s '.[0].runs += .[1].runs | .[0]' combined-${{ matrix.repo }}.sarif "$file" > temp.sarif && mv temp.sarif combined-${{ matrix.repo }}.sarif
          done

      - name: Upload Checkov SARIF Reports
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: combined-${{ matrix.repo }}.sarif
          category: analysis-${{ matrix.repo }}

      - name: Upload Zipped SARIF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-sarif-${{ matrix.repo }}.zip
          path: combined-sarif-${{ matrix.repo }}.zip
