name: Comparative Tools

on:
  push: {}

permissions:
  contents: write
  security-events: write

jobs:
  static-analysis:
    name: "Static Analysis for ${{ matrix.repo }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: 
          #- KaiMonkey-AWS
          - TerraGoat-AWS
          - TerraGoat-Azure
          - AWSGoat
          - AzureGoat

    steps:
      - name: Checkout the Main Repository
        uses: actions/checkout@v4
      
      - name: Create Infra Folder
        run: |
          mkdir infra

      - name: Clone and Move KaiMonkey Files
        if: matrix.repo == 'KaiMonkey'
        run: |
          git clone https://github.com/tenable/KaiMonkey.git
          mv KaiMonkey/terraform/aws/* infra/

      - name: Clone and Move Terragoat AWS Files
        if: matrix.repo == 'TerraGoat-AWS'
        run: |
          git clone https://github.com/octodemo/advanced-security-terraform.git
          mv advanced-security-terraform/terraform/aws/* infra/

      - name: Clone and Move Terragoat Azure Files
        if: matrix.repo == 'TerraGoat-Azure'
        run: |
          git clone https://github.com/octodemo/advanced-security-terraform.git
          mv advanced-security-terraform/terraform/azure/* infra/

      - name: Clone and Move AWSGoat Files
        if: matrix.repo == 'AWSGoat'
        run: |
          git clone https://github.com/ine-labs/AWSGoat.git
          mv AWSGoat/modules/* infra/

      - name: Clone and Move AzureGoat Files
        if: matrix.repo == 'AzureGoat'
        run: |
          git clone https://github.com/ine-labs/AzureGoat.git
          mv AzureGoat/modules/module-1/* infra/

      # Step 1: Run Checkov in silent mode
      - name: Run Checkov in silent mode
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
          output_format: sarif
          output_file_path: .
          quiet: true
        continue-on-error: true  # If Checkov fails, continue to next step

      - name: Log after Checkov
        run: |
          echo "Checkov has completed. Moving to TFSec..."
          sleep 4
          ls -lias

      # Step 2: Run TFSec
      - name: Run TFSec SARIF Report
        uses: aquasecurity/tfsec-sarif-action@v0.1.0
        with:
          sarif_file: tfsec.sarif

      - name: Log after TFSec
        run: |
          echo "TFSec has completed. Zipping the SARIF files..."
          sleep 4
          ls -la

      # Step 3: Zip all SARIF files in the directory
      - name: Zip all SARIF files
        run: |
          zip combined-sarif-${{ matrix.repo }}.zip *.sarif
          echo "Zipped all SARIF files to combined-sarif-${{ matrix.repo }}.zip"
          ls -la

      # Step 4: Upload Zipped SARIF as an artifact
      - name: Upload Zipped SARIF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-sarif-${{ matrix.repo }}.zip
          path: combined-sarif-${{ matrix.repo }}.zip